#!/usr/bin/python

import sys
import os
import re

n_max = 0
for filename in os.listdir(sys.argv[1]):

    # expected file name format: '*.N[.*]'
    tokens = filename.split('.')
    if not re.match(r'[0-9]+', tokens[1]):
        continue # skip
    n = int(tokens[1])
    if n > n_max:
        n_max = n

idx = str(n_max + 1)
print(idx)
