#!/usr/bin/bash

# Fill this in to the webserver that hosts the SpritePi HQ server info
HQ_URL=http://USER:PWD@HOST/$(hostname).txt

function kill_ssh {
	if [ ! -z "$SSH_PID" ]
	then
		echo kill $SSH_PID
		kill $SSH_PID
	fi
}

trap 'kill_ssh; exit 1' INT PIPE TERM

LAST_USER_HOST=
LAST_PORT=
SSH_PID=
while true
do

	#echo Fetching HQ server/port from $HQ_URL
	set -- $(curl -s $HQ_URL)
	if [[ "$2" =~ ^[0-9]+$ && "$1" =~ ^[0-9a-zA-Z-]+@[0-9a-zA-Z.-]+$ ]]
	then
		USER_HOST=$1
		PORT=$2
		if [[ ! ( "$USER_HOST" = "$LAST_USER_HOST" && "$PORT" = "$LAST_PORT" ) ]]
		then
			echo "HQ host/port changed, re-establishing tunnel"
			kill_ssh
			echo ssh -NT -R $PORT:localhost:22 $USER_HOST &
			ssh -NT -R $PORT:localhost:22 $USER_HOST &
			SSH_PID=$!
			LAST_USER_HOST=$USER_HOST
			LAST_PORT=$PORT
			PRINTED_INVALID=0
		fi
	else
		if [[ $PRINTED_INVALID == 0 ]]
		then
			echo Invalid HQ server/port: $1 $2
			PRINTED_INVALID=1
			LAST_USER_HOST=
			LAST_PORT=
		fi
	fi
	sleep 600
done
